<?php

namespace Rtrs\Controllers\Admin;

use Rtrs\Helpers\Functions;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class ScriptLoader {

	private $suffix;
	private $version;
	private $ajaxurl;

	function __construct() {
		$this->suffix  = ( defined( 'SCRIPT_DEBUG' ) && SCRIPT_DEBUG ) ? '' : '.min';
		$this->version = ( defined( 'WP_DEBUG' ) && WP_DEBUG ) ? time() : RTRS_VERSION;
		$this->ajaxurl = admin_url( 'admin-ajax.php' );
		add_action( 'admin_init', [ $this, 'register_admin_script' ], 1 );
		add_action( 'admin_enqueue_scripts', [ $this, 'load_admin_script_setting_page' ] );
	}

	function register_script_both_end() {
		wp_register_style( 'rtrs-app', rtrs()->get_assets_uri( 'css/app.css' ), [], $this->version );
		wp_register_script( 'featherlight', rtrs()->get_assets_uri( 'vendor/featherlight/featherlight.min.js' ), [ 'jquery' ], $this->version, true );
		wp_register_script( 'rtrs-app', rtrs()->get_assets_uri( 'js/app.js' ), [ 'jquery', 'featherlight' ], $this->version, true );

		// Dynamic Css.
		$upload_dir = wp_upload_dir();
		$cssFile    = $upload_dir['basedir'] . '/review-schema/sc.css';
		if ( file_exists( $cssFile ) ) {
			$version = filemtime( $cssFile );
			wp_register_style( 'rtrs-sc', set_url_scheme( $upload_dir['baseurl'] ) . '/review-schema/sc.css', [ 'rtrs-app' ], $version );
		}
	}

	function register_admin_script() {
		$this->register_script_both_end();

		wp_register_style( 'select2', rtrs()->get_assets_uri( 'vendor/select2/select2.min.css' ), [], $this->version );
		wp_register_style( 'rtrs-admin', rtrs()->get_assets_uri( 'css/admin.css' ), [], $this->version );
		wp_register_style( 'rtrs-settings', rtrs()->get_assets_uri( 'css/settings.css' ), [], $this->version );

		wp_register_script( 'select2', rtrs()->get_assets_uri( 'vendor/select2/select2.min.js' ), [ 'jquery' ], $this->version, true );
		wp_register_script( 'rtrs-admin', rtrs()->get_assets_uri( 'js/admin.js' ), [ 'jquery', 'wp-color-picker', 'jquery-ui-sortable' ], $this->version, true );
		wp_register_script( 'rtrs-settings', rtrs()->get_assets_uri( 'js/settings.js' ), [], $this->version, true );

		// SERP preview.
		wp_register_style( 'rtrs-serp-preview', rtrs()->get_assets_uri( 'css/serp-preview.css' ), [], $this->version );
		wp_register_script( 'rtrs-serp-preview', rtrs()->get_assets_uri( 'js/serp-preview.js' ), [], $this->version, true );
	}

	function load_admin_script_setting_page() {
		global $pagenow, $post_type;

		wp_enqueue_style( 'wp-color-picker' );
		wp_enqueue_style( 'select2' );
		wp_enqueue_style( 'rtrs-admin' );

		wp_enqueue_script( 'select2' );
		wp_enqueue_script( 'rtrs-admin' );
		wp_enqueue_media();

		wp_localize_script(
			'rtrs-admin',
			'rtrs',
			[
				'pro'              => function_exists( 'rtrsp' ),
				'nonceID'          => rtrs()->getNonceId(),
				'nonce'            => rtrs()->getNonceText(),
				'admin_nonce'      => wp_create_nonce( rtrs()->getNonceId() ),
				'ajaxurl'          => admin_url( 'admin-ajax.php' ),
				'sure_txt'         => esc_html__( 'Are you sure to delete?', 'review-schema' ),
				'criteria_alt_txt' => esc_html__( '3 criteria field are allowed for free version.', 'review-schema' ),
				'pros_alt_txt'     => esc_html__( '3 pros field are allowed for free version.', 'review-schema' ),
				'cons_alt_txt'     => esc_html__( '3 cons field are allowed for free version.', 'review-schema' ),
				'multiple_txt'     => esc_html__( 'Multiple schema are not allowed in free version.', 'review-schema' ),
				'write_txt'        => esc_html__( 'Write here!', 'review-schema' ),
				'at_least_txt'     => esc_html__( 'At least one field require', 'review-schema' ),
				'criteria_rating'  => esc_html__( '3 criteria rating field are allowed for free version.', 'review-schema' ),
				'remove_img'       => esc_html__( 'Remove Image', 'review-schema' ),
				'i18n_schema_report_loading' => esc_html__( 'Analyzing schema…', 'review-schema' ),
				'i18n_ai_notice'     => esc_html__( 'Schema is generated by AI. Please check the AI panel to view or edit.', 'review-schema' ),
				'i18n_ai_notice_sub' => esc_html__( 'After deleting AI data, manual generation fields will be visible.', 'review-schema' ),
			]
		);
	}
}
