<?php

namespace Rtrs\Controllers\Admin\Meta;

use Rtrs\Helpers\Functions;
use Rtrs\Modules\Schema\Admin\Meta\FaqPageMeta;
use Rtrs\Modules\Schema\Helpers\SerpPreviewHelper;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

class AddMetaBox {
	public function __construct() {
		// Actions.
		add_action( 'admin_head', [ $this, 'add_meta_boxes' ] );
		add_action( 'save_post', [ $this, 'save_meta_data' ], 10, 2 );
	}

	public function add_meta_boxes() {
		if ( Functions::is_edit_page() ) {
			global $post;
			$post_type = $post->post_type;
			if ( rtrs()->getPostType() === $post_type || 'rtrs_affiliate' === $post_type ) {
				return;
			}
			if ( Functions::isEnableReviewByPostType( $post_type ) || Functions::schema_enabled() ) {
				add_meta_box(
					'rtrs_meta',
					esc_html__( 'SchemaEngine AI Settings', 'review-schema' ),
					[ $this, 'rtrs_single_meta_settings' ],
					[ $post_type ],
					'normal',
					'low'
				);
			}
		}
	}

	public function postType() {
		return apply_filters( 'rtrs_post_type', Functions::getPostTypes() );
	}

	public function rtrs_single_meta_settings( $post ) {

		$post = [
			'post' => $post,
		];
		wp_nonce_field( rtrs()->getNonceId(), rtrs()->getNonceId() );
		$post_type = $post['post']->post_type;

		// auto select tab.
		$tab = get_post_meta( get_the_ID(), '_rtrs_sc_tab', true );

		if ( ! $tab ) {
			$tab = ( Functions::isEnableReviewByPostType( $post_type ) ) ? 'review' : 'schema';
		} else {
			if ( Functions::schema_enabled() && $tab == 'review' ) {
				$tab = 'schema';
			}
		}

		$is_classic_editor = ! use_block_editor_for_post( $post['post'] );

		$review_tab  = ( $tab == 'review' ) ? 'active' : '';
		$schema_tab  = ( $tab == 'schema' ) ? 'active' : '';
		$preview_tab = ( $tab == 'preview' ) ? 'active' : '';
		$serp_tab    = ( $tab == 'serp' ) ? 'active' : '';
		$faqpage_tab = ( $tab == 'faqpage' ) ? 'active' : '';

		$html  = null;
		$html .= '<div id="sc-tabs" class="rtrs-tab-container">';
		$html .= '<ul class="rtrs-tab-nav">';
		if ( Functions::isEnableReviewByPostType( $post_type ) ) {
			$html .= '<li class="' . esc_attr( $review_tab ) . '"><a href="#sc-review"><i class="dashicons dashicons-star-filled"></i>' . esc_html__( 'Review', 'review-schema' ) . '</a></li>';
		}
		if ( $is_classic_editor ) {
			$html .= '<li class="' . esc_attr( $faqpage_tab ) . '"><a href="#sc-faqpage"><i class="dashicons dashicons-format-chat"></i>' . esc_html__( 'FAQ Content', 'review-schema' ) . '</a></li>';
		}
		$html .= '<li class="' . esc_attr( $schema_tab ) . '"><a href="#sc-schema"><i class="dashicons dashicons-editor-table"></i>' . esc_html__( 'Schema and SEO Score', 'review-schema' ) . '</a></li>';
		if ( Functions::schema_enabled() ) {
			$html .= '<li class="' . esc_attr( $preview_tab ) . '"><a href="#sc-schema-preview"><i class="dashicons dashicons-editor-table"></i>' . esc_html__( 'Schema Preview', 'review-schema' ) . '</a></li>';
			$html .= '<li class="' . esc_attr( $serp_tab ) . '"><a href="#sc-serp"><i class="dashicons dashicons-search"></i>' . esc_html__( 'SERP', 'review-schema' ) . '</a></li>';
		}
		if ( Functions::schema_enabled() && 'yes' === \Rtrs\AI\AIInit::getSetting( 'ai_enabled', 'no' ) ) {
			$html .= '<li><a href="#sc-generate-ai">' . Functions::aiIconSvg( 17, 21 ) . esc_html__( 'Generate with AI', 'review-schema' ) . '</a></li>';
		}
		$html .= '</ul>';

		$review_tab    = ( 'review' === $tab ) ? 'display: block' : '';
		$schema_tab    = ( 'schema' === $tab ) ? 'display: block' : '';
		$preview_tab   = ( 'preview' === $tab ) ? 'display: block' : '';
		$serp_style    = ( 'serp' === $tab ) ? 'display: block' : '';
		$faqpage_style = ( 'faqpage' === $tab ) ? 'display: block' : '';

		$html .= '<input type="hidden" id="_rtrs_sc_tab" name="_rtrs_sc_tab" value="' . esc_attr( $tab ) . '" />';

		$html .= '<div id="sc-review" class="rtrs-tab-content" style="' . esc_attr( $review_tab ) . '">';
		if ( Functions::isEnableReviewByPostType( $post_type ) ) {
			$html .= rtrs()->render( 'metas.single.review', $post, true );
			$html .= rtrs()->render( 'metas.single.review-graph', $post, true );
		} else {
			$html .= '<div class="rtrs-preview-message"><p> <span class="dashicons dashicons-info"></span>' . esc_html__( 'Review Is Not Enabled.', 'review-schema' ) . '</p></div>';
		}
		$html .= '</div>';

		$html          .= '<div id="sc-schema" class="rtrs-tab-content" style="' . esc_attr( $schema_tab ) . '">';
		$has_ai_schema  = ! empty( get_post_meta( $post['post']->ID, \Rtrs\AI\AIInit::META_KEY, true ) );
		if ( ! Functions::schema_enabled() ) {
			$html .= '<div class="rtrs-preview-message"><p><span class="dashicons dashicons-info"></span>' . esc_html__( 'Schema Is Not Enabled.', 'review-schema' ) . '</p></div>';
		} else {
			if ( $has_ai_schema ) {
				$html .= '<div class="rtrs-ai-schema-notice">';
				$html .= '<span class="dashicons dashicons-info"></span>';
				$html .= '<div>';
				$html .= '<p>' . esc_html__( 'Schema is generated by AI. Please check the AI panel to view or edit.', 'review-schema' ) . '</p>';
				$html .= '<p>' . esc_html__( 'After deleting AI data, manual generation fields will be visible.', 'review-schema' ) . '</p>';
				$html .= '</div>';
				$html .= '</div>';
			}
			// Schema Report section. Hidden when AI schema exists — the SEO/AEO/GEO
			// analysis is shown in the AI panel in that case (matching the block
			// editor). The metabox report is the manual-schema surface only.
			$html .= '<div id="rtrs-schema-report" class="rtrs-schema-report' . ( $has_ai_schema ? ' rtrs-hidden' : '' ) . '">';
			$html .= '<div class="rtrs-schema-report__inner"></div>';
			$html .= '</div>';

			$html .= '<div class="rtrs-schema-fields' . ( $has_ai_schema ? ' rtrs-hidden' : '' ) . '">';
			$html .= rtrs()->render( 'metas.single.schema', $post, true );
			$html .= '</div>';
		}
		$html .= '</div>';

		if ( Functions::schema_enabled() ) {
			$html .= '<div id="sc-schema-preview" class="rtrs-tab-content" style="' . esc_attr( $preview_tab ) . '">';
			$html .= rtrs()->render( 'metas.single.schema-preview', $post, true );
			$html .= '</div>';
		}
		if ( Functions::schema_enabled() ) {
			if ( $is_classic_editor ) {
				$html .= '<div id="sc-faqpage" class="rtrs-tab-content" style="' . esc_attr( $faqpage_style ) . '">';
				$html .= rtrs()->render( 'metas.single.faqpage', $post, true );
				$html .= '</div>';
			}
		}
		if ( Functions::schema_enabled() ) {
			$html    .= '<div id="sc-serp" class="rtrs-tab-content" style="' . esc_attr( $serp_style ) . '">';
			$serpData = SerpPreviewHelper::extract( $post['post']->ID );
			$html    .= rtrs()->render( 'metas.single.serp-preview', compact( 'serpData' ), true );
			$html    .= '</div>';
		}
		if ( Functions::schema_enabled() && 'yes' === \Rtrs\AI\AIInit::getSetting( 'ai_enabled', 'no' ) ) {
			$html .= '<div id="sc-generate-ai" class="rtrs-tab-content">';
			$html .= '<div class="rtrs-ai-tab-message">';
			$html .= '<span class="dashicons dashicons-arrow-right-alt"></span>';
			$html .= '<p>' . esc_html__( 'Use the SchemaEngine AI panel in the right sidebar to auto-generate structured data for this post.', 'review-schema' ) . '</p>';
			$html .= '</div>';
			$html .= '</div>';
		}

		$html .= '</div>'; // wrap div
		// phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- $html is built with esc_attr/esc_html/wp_kses on dynamic parts.
		echo $html;
	}

	public function sanitize_field( $type, $value ) {
		$fValue = '';
		switch ( $type ) {
			case 'textarea':
				$fValue = isset( $value ) ? sanitize_textarea_field( $value ) : null;
				break;
			case 'text':
			case 'select':
			case 'tab':
			case 'radio-image':
				$fValue = isset( $value ) ? sanitize_text_field( $value ) : null;
				break;

			case 'url':
				$fValue = isset( $value ) ? esc_url_raw( $value ) : null;
				break;

			// A `multiple` select2 posts an array; a single one posts a string.
			case 'select2':
				if ( is_array( $value ) ) {
					$fValue = array_values( array_filter( array_map( 'sanitize_text_field', $value ) ) );
				} else {
					$fValue = isset( $value ) ? sanitize_text_field( $value ) : null;
				}
				break;

			case 'number':
			case 'switch':
			case 'checkbox':
			case 'image':
				$fValue = isset( $value ) ? absint( $value ) : null;
				break;

			case 'float':
				$fValue = isset( $value ) ? floatval( $value ) : null;
				// Numeric schema fields (price, ratings, fees, counts) are never
				// negative — clamp the minimum to 0 so a minus value can't be saved.
				if ( is_numeric( $fValue ) && $fValue < 0 ) {
					$fValue = 0;
				}
				break;

			case 'gallery':
				$fValue = isset( $value ) && is_array( $value ) ? array_map( 'absint', $value ) : null;
				break;

			case 'repeater':
				$fValue = isset( $value ) && is_array( $value ) ? array_map( 'sanitize_text_field', array_filter( $value ) ) : null;
				break;

			case 'color':
				$fValue = isset( $value ) ? sanitize_hex_color( $value ) : null;
				break;

			case 'style':
				$fValue = isset( $value ) ? array_map( 'sanitize_text_field', $value ) : null;
				break;

			default:
				$fValue = isset( $value ) ? sanitize_text_field( $value ) : null;
				break;
		}

		return $fValue;
	}

	public function searchArray( $value, $key, $array ) {
		foreach ( $array as $k => $val ) {
			if ( ! empty( $val[ $key ] ) && $val[ $key ] == $value ) {
				return $k;
			}
		}

		return null;
	}

	public function save_meta_data( $post_id, $post ) {
		if ( defined( 'DOING_AUTOSAVE' ) && DOING_AUTOSAVE ) {
			return $post_id;
		}

		if ( ! wp_verify_nonce( Functions::get_nonce(), rtrs()->getNonceId() ) ) {
			return $post_id;
		}

		$meta_options = null;
		if ( rtrs()->getPostType() == $post->post_type ) {
			$meta_options = Functions::post_type_rtrs_meta();
		} elseif ( 'rtrs_affiliate' == $post->post_type ) {
			$meta_options = Functions::affiliate_meta();
		} else {
			$meta_options    = Functions::single_page_meta_for_review_and_schema();
			$selected_schema = [];
			foreach ( $meta_options as $value ) {
				if ( in_array( ( $value['type'] ?? '' ), [ 'group', 'info' ], true ) ) {
					continue;
				}
				$selected_schema[] = $value;
			}
			if ( isset( $_POST['_rtrs_rich_snippet_cat'] ) && is_array( $_POST['_rtrs_rich_snippet_cat'] ) ) {
				$rtrs_cats = array_map( 'sanitize_text_field', wp_unslash( $_POST['_rtrs_rich_snippet_cat'] ) );
				foreach ( $rtrs_cats as $value ) {
					$index = $this->searchArray( 'rtrs_' . $value . '_schema', 'name', $meta_options );
					if ( $index != null ) {
						$selected_schema[] = $meta_options[ $index ];
					}
				}
			}

			// Re-add FAQPage dedicated group (not part of rich snippet dropdown).
			$faqpage_index = $this->searchArray( FaqPageMeta::META_KEY, 'name', $meta_options );
			if ( $faqpage_index !== null ) {
				$selected_schema[] = $meta_options[ $faqpage_index ];
			}

			$meta_options = $selected_schema;
		}
		$skip_field_types = [ 'heading', 'auto-fill' ];
		foreach ( $meta_options as $field ) {
			if ( in_array( ( $field['type'] ?? '' ), $skip_field_types, true ) ) {
				continue;
			}
			if ( $field['type'] == 'group' ) {
				// escape pro field
				if ( $field['name'] != 'rating_criteria' ) {
					if ( isset( $field['is_pro'] ) && ! function_exists( 'rtrsp' ) ) {
						continue;
					}
				}
				// save group field
				$groupValue = [];
				// remove heading type from groups field.
				foreach ( $field['fields'] as $key => $single_meta ) {
					if ( in_array( ( $single_meta['type'] ?? '' ), $skip_field_types, true ) ) {
						unset( $field['fields'][ $key ] );
					}
				}
				// after remove heading type sort again.
				$field['fields'] = array_values( $field['fields'] );
				if ( isset( $_REQUEST[ $field['name'] ] ) && is_array( $_REQUEST[ $field['name'] ] ) ) {
					// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Nested group values are sanitized per-field below via $this->sanitize_field().
					$rtrs_group_input = wp_unslash( $_REQUEST[ $field['name'] ] );
					foreach ( $rtrs_group_input as $key => $group_fields ) {
						$i = 0;
						foreach ( $group_fields as $group_key => $group_field ) {
							// if 1st nested group
							if ( $field['fields'][ $i ]['type'] == 'group' ) {
								foreach ( $group_field as $group_two_key => $group_two_field ) {
									foreach ( $group_two_field as $group_three_key => $group_three_field ) {
										$nested_index = array_search( $group_three_key, array_column( $field['fields'][ $i ]['fields'], 'name' ) );
										// if 2nd nested group
										if ( $field['fields'][ $i ]['fields'][ $nested_index ]['type'] == 'group' ) {
											foreach ( $group_three_field as $group_four_key => $group_four_field ) {
												foreach ( $group_four_field as $group_five_key => $group_five_field ) {
													$second_nested_index = array_search( $group_five_key, array_column( $field['fields'][ $i ]['fields'][ $nested_index ]['fields'], 'name' ) );
													$groupValue[ $key ][ $group_key ][ $group_two_key ][ $group_three_key ][ $group_four_key ][ $group_five_key ] = $this->sanitize_field( $field['fields'][ $i ]['fields'][ $nested_index ]['fields'][ $second_nested_index ]['type'], $group_five_field );
												}
											}
										} else {
											$groupValue[ $key ][ $group_key ][ $group_two_key ][ $group_three_key ] = $this->sanitize_field( $field['fields'][ $i ]['fields'][ $nested_index ]['type'], $group_three_field );
										}
									}
								}
							} else {
								$groupValue[ $key ][ $group_key ] = $this->sanitize_field( $field['fields'][ $i ]['type'], $group_field );
							}
							$i++;
						}
					}
				}

				// Filter out FAQ entries with empty question or answer.
				if ( $field['name'] === FaqPageMeta::META_KEY ) {
					$groupValue = array_filter(
						$groupValue,
						function ( $entry ) {
							return ! empty( trim( $entry['question'] ?? '' ) ) && ! empty( trim( $entry['answer'] ?? '' ) );
						}
					);
					$groupValue = array_values( $groupValue );
				}

				update_post_meta( $post_id, $field['name'], $groupValue );
			} else {
				if ( isset( $field['multiple'] ) ) {
					if ( $field['multiple'] ) {
						delete_post_meta( $post_id, $field['name'] );
						$mValueA = isset( $_REQUEST[ $field['name'] ] ) && is_array( $_REQUEST[ $field['name'] ] ) ? array_map( 'sanitize_text_field', wp_unslash( $_REQUEST[ $field['name'] ] ) ) : [];
						if ( is_array( $mValueA ) && ! empty( $mValueA ) ) {
							foreach ( $mValueA as $item ) {
								add_post_meta( $post_id, $field['name'], trim( $item ) );
							}
						}
					}
				} else {
					// escape pro field.
					if ( isset( $field['is_pro'] ) && ! function_exists( 'rtrsp' ) ) {
						continue;
					}
					if ( isset( $_REQUEST[ $field['name'] ] ) ) {
						// phpcs:ignore WordPress.Security.ValidatedSanitizedInput.InputNotSanitized -- Sanitized via $this->sanitize_field() per-type below.
						$rtrs_field_input = is_array( $_REQUEST[ $field['name'] ] ) ? wp_unslash( $_REQUEST[ $field['name'] ] ) : wp_unslash( $_REQUEST[ $field['name'] ] );
						$fValue           = $this->sanitize_field( $field['type'], $rtrs_field_input );
						update_post_meta( $post_id, $field['name'], $fValue );
					} elseif ( $field['type'] == 'switch' || $field['type'] == 'checkbox' ) {
						update_post_meta( $post_id, $field['name'], null );
					}
				}
			}
		}

		// Save current tab.
		$sc_tab = isset( $_REQUEST['_rtrs_sc_tab'] ) ? sanitize_text_field( wp_unslash( $_REQUEST['_rtrs_sc_tab'] ) ) : '';
		update_post_meta( $post_id, '_rtrs_sc_tab', $sc_tab );

		// Validate affiliate pricing: regular_price must be >= offer_price.
		if ( 'rtrs_affiliate' === $post->post_type ) {
			$regular_price = get_post_meta( $post_id, 'regular_price', true );
			$offer_price   = get_post_meta( $post_id, 'offer_price', true );

			if ( '' !== $regular_price && '' !== $offer_price && is_numeric( $regular_price ) && is_numeric( $offer_price ) ) {
				if ( floatval( $regular_price ) < floatval( $offer_price ) ) {
					// Swap the prices so regular is always >= offer.
					update_post_meta( $post_id, 'regular_price', $offer_price );
					update_post_meta( $post_id, 'offer_price', $regular_price );
					set_transient( 'rtrs_admin_notice', esc_html__( 'Regular Price cannot be less than Offer Price. The values have been swapped automatically.', 'review-schema' ), 30 );
				}
			}
		}

		// generate shortcode.
		if ( rtrs()->getPostType() == $post->post_type ) {
			Functions::generatorShortCodeCss( $post_id, 'review' );
		} elseif ( 'rtrs_affiliate' == $post->post_type ) {
			Functions::generatorShortCodeCss( $post_id, 'affiliate' );
		}
	} // end function
}
