<?php

namespace Rtrs\Modules\Schema\Hooks;

use Rtrs\AI\AIInit;
use Rtrs\Helpers\Functions;
use Rtrs\Modules\Schema\Models\Schema;
use Rtrs\Traits\SingletonTrait;

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

/**
 * Handles the frontend implementation of schema functionality.
 */
class SchemaFrontend {
	/**
	 * SingleTon
	 */
	use SingletonTrait;

	/**
	 * Schema Enabled.
	 */
	private function __construct() {
		add_action( 'wp_head', [ $this, 'google_rich_snippet' ], 1 );
	}
	/**
	 * @return void
	 */
	public function google_rich_snippet() {
		if ( ! Functions::schema_enabled() ) {
			return;
		}
		$post_id = get_queried_object_id();

		// Skip if AI schema is enabled and this is a singular post — AI renderer handles it.
		if ( is_singular() && 'yes' === AIInit::getSetting( 'ai_enabled', 'no' ) ) {
			$ai_data = AIInit::normalizeSchemaData( get_post_meta( $post_id, AIInit::META_KEY, true ) );

			if ( ! empty( $ai_data ) ) {
				return;
			}
		}

		// Bail if no valid post ID (archives, search, 404, etc).
		$snippet      = new Schema( $post_id );
		$rich_snippet = $snippet->header_schema_data();
		if ( $rich_snippet ) {
			echo "\n" . '<!-- This Google structured data (Rich Snippet) generated by SchemaEngine AI plugin version ' . esc_html( RTRS_VERSION ) . ' -->' . "\n" . $rich_snippet . "\n"; // phpcs:ignore WordPress.Security.EscapeOutput.OutputNotEscaped -- $rich_snippet is pre-built JSON-LD script tag and must not be escaped.
		}
	}
}
